server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://mysql-17f0b469-suhanmuhammed4-ea38.h.aivencloud.com:15753/coursemedia?createDatabaseIfNotExist=true


    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

#  mvc:
#    path-match:
#      matching-strategy: ANT_PATH_MATCHER

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false



JWT_KEY: BF7FD11ACE545745B7BA1AF98B6F156D127BC7BB544BAB6A4FD74E4FC7
